name: Build and Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  #name of job  
 npm_security_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout of the repo
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install Dependencies
      run: npm install
    - name: Run Integration Tests
      run: npm run test-npm-security

    #name of job
  integration_tests:
    runs-on: ubuntu-latest

    needs: npm_security_tests
    steps:
       ## Initialize the repo
    - name: Checkout of the repo
      uses: actions/checkout@v4
      ## Define version of Node.js
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
       ## Install тхе necessary libraries
    - name: Install Dependencies
      run: npm install
      ## Run the integration test with define command into package.json file
    - name: Run Integration Tests
      run: npm test
